apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managers

commonAnnotations:
  k0s.reynn.net/base: sonarr

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - storage.yaml
