apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  annotations:
    k0s.reynn.net/resource-profile: small
    k0s.reynn.net/host: mimikyu
spec:
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
        - name: nzbget
          image: linuxserver/nzbget
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: TZ
              value: America/Los Angeles
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-wait-for-internet
          resources: {}
          ports:
            - containerPort: 6789
              name: tcp-server
          volumeMounts:
            - name: downloads
              mountPath: /media/deadpool/downloads
            - name: config
              mountPath: /config
            - name: temp-nzbs
              mountPath: /media/deadpool/nzbs
      volumes:
        - name: downloads
          hostPath:
            path: /media/deadpool/downloads
            type: Directory
        - name: config
          hostPath:
            path: /media/server/nzbget/
            type: Directory
        - name: temp-nzbs
          emptyDir: {}
