apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  annotations:
    k0s.reynn.net/resource-profile: small
spec:
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - mimikyu
      containers:
        - name: nzbget
          image: linuxserver/nzbget
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: TZ
              value: America/Los Angeles
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-wait-for-internet
          resources: {}
          ports:
            - containerPort: 6789
              name: tcp-server
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media/deadpool/downloads
              name: media
            - mountPath: /media/deadpool/nzbs
              name: temp-nzbs
      volumes:
        - name: media
          hostPath:
            path: /media/deadpool/downloads/
            type: Directory
        - name: temp-nzbs
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
