apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonAnnotations:
  k0s.reynn.net/base: jellyfin

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
