apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: jellyfin/jellyfin
    newTag: "10.7.2"
  - name: dperson/samba
    newTag: latest
  - name: linuxserver/radarr
    newName: ghcr.io/linuxserver/radarr
    newTag: nightly
  - name: linuxserver/jackett
    newName: ghcr.io/linuxserver/jackett
    newTag: development
  - name: linuxserver/nzbhydra
    newName: ghcr.io/linuxserver/nzbhydra2
    newTag: latest
  - name: linuxserver/lidarr
    newName: ghcr.io/linuxserver/lidarr
    newTag: nightly
  - name: linuxserver/sonarr
    newName: ghcr.io/linuxserver/sonarr
    newTag: develop
  - name: linuxserver/nzbget
    newName: ghcr.io/linuxserver/nzbget
    newTag: testing
  - name: linuxserver/calibre-web
    newName: ghcr.io/linuxserver/calibre-web
    newTag: latest
  - name: linuxserver/mylar3
    newName: ghcr.io/linuxserver/mylar3
    newTag: nightly
  - name: linuxserver/qbittorrent
    newName: ghcr.io/linuxserver/qbittorrent
    newTag: unstable

secretGenerator:
  - name: reynn-net-cert
    type: kubernetes.io/tls
    options:
      disableNameSuffixHash: true
    files:
      - tls.crt
      - tls.key

# Memory Profiles for deployments
# small, mid, large,
patches:
  - path: patches.json/resource.limits.small.yaml
    target:
      annotationSelector: "mimikyu.reynn.net/resource-profile=small"
      group: apps
      kind: Deployment
      version: v1
  - path: patches.json/resource.limits.mid.yaml
    target:
      annotationSelector: "mimikyu.reynn.net/resource-profile=mid"
      group: apps
      kind: Deployment
      version: v1
  - path: patches.json/resource.limits.large.yaml
    target:
      annotationSelector: "mimikyu.reynn.net/resource-profile=large"
      group: apps
      kind: Deployment
      version: v1
  - path: patches.json/resource.limits.deluxe.yaml
    target:
      annotationSelector: "mimikyu.reynn.net/resource-profile=deluxe"
      group: apps
      kind: Deployment
      version: v1

bases:
  - bases/calibre
  - bases/jackett
  - bases/jellyfin
  - bases/lidarr
  - bases/mylar
  - bases/nzbget
  # - bases/nzbhydra
  - bases/qbittorrent
  - bases/radarr
  - bases/samba
  - bases/sonarr
  - bases/traefik
