namespace: default

commonAnnotations:
  k0s.reynn.net/base: onedev

helmCharts:
  - name: onedev
    includeCRDs: true
    releaseName: onedev
    valuesFile: helm.values.yaml
    repo: https://dl.cloudsmith.io/public/onedev/onedev/helm/charts
    version: "7.4.24"

resources:
  - ingress.yaml
