namespace: utils

commonAnnotations:
  k0s.reynn.net/base: vpn-gateway
  k0s.reynn.net/host: mimikyu

helmCharts:
  - name: pod-gateway
    repo: https://k8s-at-home.com/charts
    includeCRDs: true
    releaseName: pod-gateway
    valuesFile: helm.values.yaml
    version: 5.6.2

configMapGenerator:
  - name: openvpn-config
    namespace: utils
    options:
      disableNameSuffixHash: true
    files:
      - vpnConfigfile=us9130.nordvpn.com.tcp443.ovpn
