apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: music-video-updater
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: music-video-downloader
              image: python3
              command:
                - "/bin/sh"
                - "-c"
                - "python3 install -U youtube-dl"
                - |
                  youtube-dl --config-location /config/youtube.dl.properties \
                    --download-archive "/videos/youtube.archive.txt"
          volumeMounts:
            - name: config
              mountPath: /config
        volumes:
          - name: config
            configMap:
              name: music-video-configs
              items:
                - key: youtube.batch.txt
                  path: youtube.batch.txt
                - key: youtube.dl.properties
                  path: youtube.dl.properties
