commonAnnotations:
  k0s.reynn.net/base: jobs
  k0s.reynn.net/job: music-video-updater

resources:
  - cron.job.yaml

configMapGenerator:
  - name: music-video-configs
    options:
      disableNameSuffixHash: true
    files:
      - config/youtube.batch.txt
      - config/youtube.dl.properties
