apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
spec:
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k3s.io/hostname
                    operator: In
                    values:
                      - mimikyu
      containers:
        - name: samba
          image: dperson/samba
          envFrom:
            - configMapRef:
                name: samba-config
          resources: {}
          ports:
            - containerPort: 139
              name: tcp-server
          volumeMounts:
            - mountPath: /media/deadpool
              name: data
      volumes:
        - name: data
          hostPath:
            path: /media/deadpool/
            type: Directory
