apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - args:
            - --web.listen-address=0.0.0.0:9090
            - --config.file=/etc/prometheus/prometheus.yaml
            - --storage.tsdb.path=/var/lib/prometheus
            - --storage.tsdb.retention.time=2d
            - --storage.tsdb.retention.size=5GB
            - --storage.tsdb.min-block-duration=2h
            - --storage.tsdb.max-block-duration=2h
          image: quay.io/prometheus/prometheus:v2.19.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: prometheus
          ports:
            - containerPort: 9090
              name: web
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/prometheus
              name: config
            - mountPath: /etc/prometheus/rules
              name: rules
            - mountPath: /var/lib/prometheus
              name: data
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - chown
            - -R
            - 65534:65534
            - /var/lib/prometheus
          image: docker.io/alpine:3.9
          imagePullPolicy: IfNotPresent
          name: chown
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/prometheus
              name: data
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: prometheus-config
        - name: rules
          configMap:
            defaultMode: 420
            name: prometheus-rules
        - name: data
          emptyDir: {}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: prometheus
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    name: prometheus
  type: ClusterIP
