apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  k0s.reynn.net/overlay: secrets

secretGenerator:
  - name: reynn-net-cert
    namespace: default
    type: kubernetes.io/tls
    options: { disableNameSuffixHash: true }
    files:
      - tls.crt=ssl/domain.cert.pem
      - tls.key=ssl/private.key.pem
  - name: reynn-net-cert
    namespace: downloaders
    type: kubernetes.io/tls
    options: { disableNameSuffixHash: true }
    files:
      - tls.crt=ssl/domain.cert.pem
      - tls.key=ssl/private.key.pem
  - name: reynn-net-cert
    namespace: managers
    type: kubernetes.io/tls
    options: { disableNameSuffixHash: true }
    files:
      - tls.crt=ssl/domain.cert.pem
      - tls.key=ssl/private.key.pem
  - name: reynn-net-cert
    namespace: utils
    type: kubernetes.io/tls
    options: { disableNameSuffixHash: true }
    files:
      - tls.crt=ssl/domain.cert.pem
      - tls.key=ssl/private.key.pem
