apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  k0s.reynn.net/overlay: secrets

secretGenerator:
  - name: reynn-net-cert
    options:
      disableNameSuffixHash: true
    namespace: downloaders
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"
  - name: reynn-net-cert
    options:
      disableNameSuffixHash: true
    namespace: managers
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"
  - name: reynn-net-cert
    options:
      disableNameSuffixHash: true
    namespace: utils
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"
