apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylar
  annotations:
    k0s.reynn.net/resource-profile: small
    k0s.reynn.net/host: mimikyu
spec:
  selector:
    matchLabels:
      app: mylar
  template:
    metadata:
      labels:
        app: mylar
    spec:
      containers:
        - name: mylar
          image: linuxserver/mylar3
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: TZ
              value: America/Los Angeles
          resources: {}
          ports:
            - containerPort: 8090
              name: tcp-server
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /comics
              name: comics
      volumes:
        - name: comics
          hostPath:
            path: /media/deadpool/comics
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /media/server/mylar
            type: Directory
