apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylar
  annotations:
    k0s.reynn.net/resource-profile: small
spec:
  selector:
    matchLabels:
      app: mylar
  template:
    metadata:
      labels:
        app: mylar
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - mimikyu
      containers:
        - name: mylar
          image: linuxserver/mylar3
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: TZ
              value: America/Los Angeles
          resources: {}
          ports:
            - containerPort: 8090
              name: tcp-server
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /comics
              name: comics
      volumes:
        - name: comics
          hostPath:
            path: /media/deadpool/comics
            type: DirectoryOrCreate
        - name: config
          persistentVolumeClaim:
            claimName: mylar-config
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mylar-config
#   labels:
#     app: mylar-config
# spec:
#   storageClassName: longhorn
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
