image:
  pullPolicy: Always

# Default values for the caddy ingress controller.
ingressController:
  watchNamespace: ""
  config:
    debug: false
    email: arasureynn@gmail.com
    metrics: true

loadBalancer:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 750m
    memory: 5128Mi
  requests:
    cpu: 500m
    memory: 128Mi
