apiVersion: v1
kind: Service
metadata:
  name: jackett
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  selector:
    app: jackett
  ports:
    - name: tcp
      port: 9117
      # nodePort: 32767
