apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: downloaders

commonAnnotations:
  k3s.reynn.net/base: qbittorrent

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
