apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-provisioner
  labels:
    name: openebs-provisioner
    openebs.io/component-name: openebs-provisioner
    openebs.io/version: 2.8.0
spec:
  selector:
    matchLabels:
      name: openebs-provisioner
      openebs.io/component-name: openebs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: openebs-provisioner
        openebs.io/component-name: openebs-provisioner
        openebs.io/version: 2.8.0
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
        - name: openebs-provisioner
          imagePullPolicy: IfNotPresent
          image: openebs/openebs-k8s-provisioner:2.8.0
          env:
            # OPENEBS_IO_K8S_MASTER enables openebs provisioner to connect to K8s
            # based on this address. This is ignored if empty.
            # This is supported for openebs provisioner version 0.5.2 onwards
            #- name: OPENEBS_IO_K8S_MASTER
            #  value: "http://10.128.0.12:8080"
            # OPENEBS_IO_KUBE_CONFIG enables openebs provisioner to connect to K8s
            # based on this config. This is ignored if empty.
            # This is supported for openebs provisioner version 0.5.2 onwards
            #- name: OPENEBS_IO_KUBE_CONFIG
            #  value: "/home/ubuntu/.kube/config"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPENEBS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # OPENEBS_MAYA_SERVICE_NAME provides the maya-apiserver K8s service name,
            # that provisioner should forward the volume create/delete requests.
            # If not present, "maya-apiserver-service" will be used for lookup.
            # This is supported for openebs provisioner version 0.5.3-RC1 onwards
            #- name: OPENEBS_MAYA_SERVICE_NAME
            #  value: "maya-apiserver-apiservice"
            # LEADER_ELECTION_ENABLED is used to enable/disable leader election. By default
            # leader election is enabled.
            #- name: LEADER_ELECTION_ENABLED
            #  value: "true"
            # OPENEBS_IO_JIVA_PATCH_NODE_AFFINITY is used to enable/disable setting node affinity
            # to the jiva replica deployments. Default is `enabled`. The valid values are
            # `enabled` and `disabled`.
            #- name: OPENEBS_IO_JIVA_PATCH_NODE_AFFINITY
            #  value: "enabled"
            # Process name used for matching is limited to the 15 characters
            # present in the pgrep output.
            # So fullname can't be used here with pgrep (>15 chars).A regular expression
            # that matches the entire command name has to specified.
            # Anchor `^` : matches any string that starts with `openebs-provis`
            # `.*`: matches any string that has `openebs-provis` followed by zero or more char
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - test `pgrep -c "^openebs-provisi.*"` = 1
            initialDelaySeconds: 30
            periodSeconds: 60
          resources: {}
