apiVersion: v1
kind: Namespace
metadata:
  name: downloaders
---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: v1
kind: Namespace
metadata:
  name: managers
---
apiVersion: v1
kind: Namespace
metadata:
  name: utils
  labels:
    routed-gateway: "true"
