apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  annotations:
    k0s.reynn.net/resource-profile: small
    k0s.reynn.net/host: mimikyu
spec:
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: linuxserver/lidarr
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: TZ
              value: America/Los Angeles
          resources: {}
          ports:
            - containerPort: 8686
              name: tcp-server
          volumeMounts:
            - name: config
              mountPath: /config
            - name: music
              mountPath: /media/deadpool/music
            - name: downloads
              mountPath: /media/deadpool/downloads
      volumes:
        - name: music
          hostPath:
            path: /media/deadpool/music
            type: Directory
        - name: downloads
          hostPath:
            path: /media/deadpool/downloads
            type: Directory
        - name: config
          hostPath:
            path: /media/server/lidarr
            type: Directory
