apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  annotations:
    k0s.reynn.net/resource-profile: mini
spec:
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - mimikyu
      containers:
        - name: calibre
          image: linuxserver/calibre-web
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DOCKER_MODS
              value: linuxserver/calibre-web:calibre
            - name: TZ
              value: America/Los Angeles
          resources: {}
          ports:
            - containerPort: 8083
              name: tcp-http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media/deadpool
              name: media
      volumes:
        - name: media
          hostPath:
            path: /media/deadpool/
            type: Directory
        - name: config
          persistentVolumeClaim:
            claimName: calibre-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  labels:
    app: calibre-config
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
