apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  annotations:
    k0s.reynn.net/resource-profile: mini
    k0s.reynn.net/host: mimikyu
spec:
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre
          image: linuxserver/calibre-web
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DOCKER_MODS
              value: linuxserver/calibre-web:calibre
            - name: TZ
              value: America/Los Angeles
          resources: {}
          ports:
            - containerPort: 8083
              name: tcp-http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media/deadpool
              name: media
      volumes:
        - name: media
          hostPath:
            path: /media/deadpool/
            type: Directory
        - name: config
          hostPath:
            path: /media/server/calibre/
            type: Directory
