apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managers

commonAnnotations:
  k3s.reynn.net/base: calibre-web

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
