apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  k3s.reynn.net/base: longhorn

namespace: longhorn-system

resources:
  - ingress.route.yaml
  - longhorn-backend-svc.yaml
  - longhorn-bind-crb.yaml
  - longhorn-driver-deployer-deployment.yaml
  - longhorn-frontend-svc.yaml
  - longhorn-manager-daemonset.yaml
  - longhorn-psp-binding-rb.yaml
  - longhorn-psp-podsecuritypolicy.yaml
  - longhorn-psp-role-role.yaml
  - longhorn-role-cr.yaml
  - longhorn-service-account-sa.yaml
  - longhorn-system-namespace.yaml
  - longhorn-ui-deployment.yaml
  - crds/engineimages.longhorn.io-crd.yaml
  - crds/engines.longhorn.io-crd.yaml
  - crds/instancemanagers.longhorn.io-crd.yaml
  - crds/nodes.longhorn.io-crd.yaml
  - crds/replicas.longhorn.io-crd.yaml
  - crds/settings.longhorn.io-crd.yaml
  - crds/sharemanagers.longhorn.io-crd.yaml
  - crds/volumes.longhorn.io-crd.yaml

configMapGenerator:
  - name: longhorn-settings
    files:
      - configs/settings.yaml
  - name: longhorn-storageclass
    options:
      disableNameSuffixHash: true
    files:
      - configs/storageclass.yaml

secretGenerator:
  - name: longhorn-s3-token
    options:
      disableNameSuffixHash: true
    envs:
      - "s3-token.properties"
