apiVersion: v1
kind: Namespace
metadata:
  name: downloaders
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: managers
---
apiVersion: v1
kind: Namespace
metadata:
  name: utils
