kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  # diskSelector: "ssd,fast"
  # nodeSelector: "storage,fast"
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 0 ? * SUN", "retain":3},
    {"name":"backup", "task":"backup", "cron":"0 */12 * * *", "retain":5}]'
