apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

commonAnnotations:
  k0s.reynn.net/base: pihole

resources:
  - deployment.yaml
  - service.yaml
  - ingress.route.yaml
  - dns.pvc.yaml
  - config.pvc.yaml
