apiVersion: wolfs.io/v1beta1
kind: HelmChart
metadata:
  name: metallb
  namespace: utils

chart:
  git: https://github.com/bitnami/charts.git
  ref: master
  path: bitnami/metallb/

values:
  # https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml
  configInline: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 10.40.0.90-10.40.0.200
  prometheus:
    scrapeAnnotations: true
  podMonitor:
    # enable support for Prometheus Operator
    enabled: false
  speaker:
    enabled: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
