apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

commonAnnotations:
  k0s.reynn.net/base: metallb

generators:
  - helm.chart.yaml

patchesJson6902:
  - path: crb.ns.json-patch.yaml
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: metallb
      version: v1
