namespace: utils

commonAnnotations:
  k0s.reynn.net/base: cert-manager
  k0s.reynn.net/host: mimikyu

helmCharts:
  - includeCRDs: true
    name: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    version: v1.10.0
    valuesFile: helm.values.yaml
